let data = [
    {
        id : 'mg20',
        name : 'Manvitha',
        age : 20,
        gender : 'Female',
        vehicle : 'Swift dzire',
        seats : 3,
        from : 'Srirangapatna',
        to : 'Banglore',
        price : 290,
        isInstant : false,
        departureTime : '14:20',
        reachTime : '16:45'
    },
    {
        id : 'mg20',
        name : 'Ajith',
        age : 22,
        gender : 'Male',
        vehicle : 'maruthi eritiga',
        seats : 0,
        from : 'Mysore',
        to : 'Banglore',
        price : 350,
        isInstant : true,
        departureTime : '4:20',
        reachTime : '6:45'
    },
    {
        id : 'mg20',
        name : 'Sathvik',
        age : 22,
        gender : 'Male',
        vehicle : 'maruthi eritiga',
        seats : 1,
        from : 'Mysore',
        to : 'Banglore',
        price : 320,
        isInstant : true,
        departureTime : '5:20',
        reachTime : '7:45'
    },
    {
        id : 'mg20',
        name : 'Sathvik',
        age : 22,
        gender : 'Male',
        vehicle : 'maruthi eritiga',
        seats : 1,
        from : 'Mysore',
        to : 'Banglore',
        price : 320,
        isInstant : true,
        departureTime : '5:20',
        reachTime : '7:45'
    },
    {
        id : 'mg20',
        name : 'Sathvik',
        age : 22,
        gender : 'Male',
        vehicle : 'maruthi eritiga',
        seats : 1,
        from : 'Mysore',
        to : 'Banglore',
        price : 320,
        isInstant : true,
        departureTime : '5:20',
        reachTime : '7:45'
    },
    {
        id : 'mg20',
        name : 'Sathvik',
        age : 22,
        gender : 'Male',
        vehicle : 'maruthi eritiga',
        seats : 1,
        from : 'Mysore',
        to : 'Banglore',
        price : 320,
        isInstant : true,
        departureTime : '5:20',
        reachTime : '7:45'
    },
]

export default data;